include:
    - 'https://gitlab.com/danielrvelasquez/pipelines/raw/master/.ci-pipeline-template.yml'
    - 'https://gitlab.com/danielrvelasquez/pipelines/raw/master/.ci-terraform-multitier-app.yml'
    - 'https://gitlab.com/danielrvelasquez/pipelines/raw/master/.ci-aks-multilayer-app.yml'